from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

MARKING_DATA ={"name":"0a0peKbxr","marks":12},{"name":"F","marks":12},{"name":"LQ","marks":73},{"name":"qSBBR5Ga","marks":9},{"name":"I","marks":64},{"name":"jEwPI","marks":68},{"name":"XF8","marks":67},{"name":"OUl","marks":43},{"name":"ADQduYm8gf","marks":67},{"name":"bXX","marks":83},{"name":"V","marks":55},{"name":"AxnOq9sck","marks":65},{"name":"h","marks":32},{"name":"a8O3aokTEA","marks":56},{"name":"hO3XtN","marks":53},{"name":"RdMqsUkkr","marks":39},{"name":"ciVtdzj","marks":76},{"name":"mXS","marks":89},{"name":"V","marks":62},{"name":"CuYaUJ8GPV","marks":33},{"name":"p1A5","marks":50},{"name":"84OOw","marks":82},{"name":"G","marks":55},{"name":"irc5WyF","marks":73},{"name":"0znc","marks":7},{"name":"E","marks":33},{"name":"I1sXw3D8","marks":4},{"name":"d7i","marks":76},{"name":"0vLSifbas","marks":37},{"name":"JHwK5p","marks":15},{"name":"Z","marks":49},{"name":"SjqXM","marks":64},{"name":"E0p","marks":61},{"name":"0QjktghLB","marks":24},{"name":"dPaQSz","marks":58},{"name":"3ontDi","marks":60},{"name":"vhYw7","marks":4},{"name":"84SfUbO4xa","marks":72},{"name":"GIPRO","marks":12},{"name":"EJMPHw","marks":37},{"name":"p","marks":22},{"name":"ndbU9","marks":65},{"name":"JKD7R8QEmG","marks":85},{"name":"VG","marks":14},{"name":"l","marks":65},{"name":"yJ","marks":17},{"name":"prz","marks":58},{"name":"3","marks":46},{"name":"vlFk1B1CIz","marks":28},{"name":"Ede6aGp","marks":34},{"name":"22","marks":35},{"name":"bGYAHlS0eK","marks":32},{"name":"1WTyOR","marks":1},{"name":"J","marks":13},{"name":"UQJJ","marks":2},{"name":"0Qgo8A","marks":10},{"name":"InPSE","marks":86},{"name":"yYAmH4AywG","marks":64},{"name":"QT","marks":77},{"name":"EP","marks":42},{"name":"RI7kUQ","marks":72},{"name":"LqFYAScoTU","marks":54},{"name":"OeKAdFN","marks":43},{"name":"KBJJWfOu","marks":14},{"name":"Fk0","marks":45},{"name":"f45","marks":42},{"name":"oHSM1Q","marks":57},{"name":"xR3iVAfd","marks":83},{"name":"YG7iKl","marks":97},{"name":"hUQJloAyfj","marks":3},{"name":"cglrC","marks":2},{"name":"ejva0vkCvc","marks":1},{"name":"rFl","marks":47},{"name":"F","marks":11},{"name":"yRy6AKA","marks":3},{"name":"v","marks":52},{"name":"ay1uqVG8","marks":33},{"name":"VIy57Riha","marks":28},{"name":"s","marks":42},{"name":"PhPS6F4q2s","marks":87},{"name":"Zfeu","marks":62},{"name":"E26SXqt","marks":10},{"name":"gH","marks":73},{"name":"EAN1Pxx","marks":7},{"name":"8NNjNZx","marks":46},{"name":"rHtZA7EAvZ","marks":9},{"name":"OWX7doaE9","marks":24},{"name":"ofLJoyw","marks":77},{"name":"qMXhr1s","marks":76},{"name":"4y4EI4Xr","marks":12},{"name":"3R0FXDVs","marks":34},{"name":"GROaa","marks":44},{"name":"og","marks":60},{"name":"r8","marks":6},{"name":"LU1mm","marks":11},{"name":"STRkCK3","marks":12},{"name":"y3x8","marks":83},{"name":"w5BPUS","marks":59},{"name":"p0r","marks":53},{"name":"kHmo","marks":96}

@app.route('/api')
def get_marks():
    names = request.args.getlist('name')
    marks = [MARKING_DATA.get(name, 0) for name in names]
    return jsonify({"marks": marks})